# Generated by Django 2.2.2 on 2019-07-03 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='color',
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 3, 2, 47, 53, 449090)),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_name',
            field=models.TextField(default='nofile'),
        ),
    ]
